name: codesapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  image_picker: ^1.0.7

  inview_notifier_list: ^3.0.0
  get_it: ^8.0.3
  lottie: ^3.1.0
  particles_fly: ^0.0.8
  carousel_slider: ^5.0.0
  superellipse_shape: ^0.2.0
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.0
  sidebarx: ^0.17.1
  visibility_detector: ^0.4.0+2
  video_player: ^2.9.5
  firebase_core: ^3.13.0
  neopop: ^1.0.2


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/


